"""
LarkFlow skill-routing 文档生成脚本

输入：
1. rules/skill-routing.yaml 中的路由定义（canonical source）

输出：
1. rules/skill-routing.md（人类可读镜像）

用法：
    python scripts/gen_skill_routing_md.py
    python scripts/gen_skill_routing_md.py --check
"""

import argparse
import sys
from pathlib import Path
from typing import Any, Optional

import yaml


PROJECT_ROOT = Path(__file__).resolve().parents[1]
ROUTING_YAML_PATH = PROJECT_ROOT / "rules" / "skill-routing.yaml"
ROUTING_MD_PATH = PROJECT_ROOT / "rules" / "skill-routing.md"

AUTO_GENERATED_HEADER = (
    "<!-- AUTO-GENERATED FROM rules/skill-routing.yaml by "
    "scripts/gen_skill_routing_md.py, DO NOT EDIT -->"
)
BOLD_WEIGHT_THRESHOLD = 1.1
SKILL_PATH_PREFIX = "skills/"


def load_routing(path: Path = ROUTING_YAML_PATH) -> dict[str, Any]:
    """
    读取并解析 skill-routing.yaml

    @params:
        path: YAML 文件路径

    @return:
        解析后的顶层 dict，至少包含 routes 与 defaults 键
    """
    with path.open("r", encoding="utf-8") as handle:
        return yaml.safe_load(handle) or {}


def _format_weight(weight: float) -> str:
    """
    将权重格式化为 md 单元格文本；>= 1.1 加粗

    @params:
        weight: 原始权重

    @return:
        md 字符串，例如 '1.0' 或 '**1.3**'
    """
    text = f"{weight:.1f}"
    if weight >= BOLD_WEIGHT_THRESHOLD:
        return f"**{text}**"
    return text


def _format_display_keywords(route: dict[str, Any]) -> str:
    """
    取 route 的展示关键词，缺省时回落到 keywords 原样逗号拼接

    @params:
        route: 单条 route dict

    @return:
        md 单元格中 Keywords/Domain 列的文本
    """
    display = route.get("display_keywords")
    if display:
        return str(display).strip()
    return ", ".join(route.get("keywords", []))


def render_skill_routing_markdown(data: dict[str, Any]) -> str:
    """
    将路由数据渲染为 skill-routing.md 文本

    @params:
        data: load_routing() 返回的 dict

    @return:
        完整的 skill-routing.md 文本内容
    """
    routes: list[dict[str, Any]] = data.get("routes", []) or []
    defaults: list[str] = data.get("defaults", []) or []

    lines: list[str] = [
        AUTO_GENERATED_HEADER,
        "",
        "# Skill Routing Table",
        "",
        "> **⚠️ Source of truth**: `rules/skill-routing.yaml`. This Markdown file is a",
        "> human-readable mirror generated by `scripts/gen_skill_routing_md.py` — if the",
        "> two disagree, the YAML wins. When adding or changing a route, edit the YAML",
        "> and regenerate this file.",
        "",
        (
            "**Rule**: When the user's requirement or the technical design involves the "
            "following keywords, you **MUST IMMEDIATELY** use the `file_editor` tool to "
            "read the corresponding `Ref File` before writing any code. When multiple "
            "routes match, read them in descending order of `weight` (framework skills "
            "1.3, business 1.2, generic 1.0)."
        ),
        "",
        "| Keywords / Domain | Ref File | Weight | Description |",
        "|-------------------|----------|--------|-------------|",
    ]

    for route in routes:
        keywords_cell = _format_display_keywords(route)
        skill_cell = f"`{route['skill']}`"
        weight_cell = _format_weight(float(route.get("weight", 1.0)))
        description_cell = str(route.get("description", "") or "").strip()
        lines.append(
            f"| {keywords_cell} | {skill_cell} | {weight_cell} | {description_cell} |"
        )

    lines.extend(
        [
            "",
            f"**Path Prefix**: `{SKILL_PATH_PREFIX}` (relative to the workspace root)",
            "",
        ]
    )

    if defaults:
        defaults_text = ", ".join(f"`{item}`" for item in defaults)
        lines.append(
            f"**Defaults** (read when nothing else matches): {defaults_text}"
        )

    return "\n".join(lines) + "\n"


def write_skill_routing(
    yaml_path: Path = ROUTING_YAML_PATH,
    md_path: Path = ROUTING_MD_PATH,
) -> Path:
    """
    生成并写入 skill-routing.md

    @params:
        yaml_path: 源 YAML 路径
        md_path: 目标 md 路径

    @return:
        实际写入的文件路径
    """
    content = render_skill_routing_markdown(load_routing(yaml_path))
    md_path.write_text(content, encoding="utf-8")
    return md_path


def check_skill_routing(
    yaml_path: Path = ROUTING_YAML_PATH,
    md_path: Path = ROUTING_MD_PATH,
) -> bool:
    """
    校验 skill-routing.md 是否与 YAML 一致

    @params:
        yaml_path: 源 YAML 路径
        md_path: 目标 md 路径

    @return:
        一致返回 True，否则 False
    """
    expected = render_skill_routing_markdown(load_routing(yaml_path))
    actual = md_path.read_text(encoding="utf-8") if md_path.exists() else ""
    return actual == expected


def main(argv: Optional[list[str]] = None) -> int:
    """
    运行路由文档生成或一致性校验

    @params:
        argv: 可选命令行参数列表

    @return:
        成功 0；校验失败 1
    """
    parser = argparse.ArgumentParser(
        description=(
            "Generate or check rules/skill-routing.md from rules/skill-routing.yaml"
        ),
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if rules/skill-routing.md is not up to date",
    )
    args = parser.parse_args(argv)

    if args.check:
        if check_skill_routing():
            print(f"Up to date: {ROUTING_MD_PATH}")
            return 0
        print(
            "rules/skill-routing.md is out of date. "
            "Run `python scripts/gen_skill_routing_md.py` to regenerate it.",
            file=sys.stderr,
        )
        return 1

    output_path = write_skill_routing()
    print(f"Generated {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
