"""
LarkFlow skill-routing 文档生成脚本

输入：
1. rules/skill-routing.yaml 中的路由定义（canonical source）

输出：
1. rules/skill-routing.md（人类可读镜像）

用法：
    python scripts/gen_skill_routing_md.py
    python scripts/gen_skill_routing_md.py --check
"""

import argparse
import sys
from pathlib import Path
from typing import Any, Optional

import yaml


PROJECT_ROOT = Path(__file__).resolve().parents[1]
ROUTING_YAML_PATH = PROJECT_ROOT / "rules" / "skill-routing.yaml"
ROUTING_MD_PATH = PROJECT_ROOT / "rules" / "skill-routing.md"

AUTO_GENERATED_HEADER = (
    "<!-- AUTO-GENERATED FROM rules/skill-routing.yaml by "
    "scripts/gen_skill_routing_md.py, DO NOT EDIT -->"
)
BOLD_WEIGHT_THRESHOLD = 1.1
SKILL_PATH_PREFIX = "skills/"


def load_routing(path: Path = ROUTING_YAML_PATH) -> dict[str, Any]:
    """
    读取并解析 skill-routing.yaml

    @params:
        path: YAML 文件路径

    @return:
        解析后的顶层 dict，包含 baseline / conditional / routes 等键
    """
    with path.open("r", encoding="utf-8") as handle:
        return yaml.safe_load(handle) or {}


def _format_weight(weight: float) -> str:
    """权重 >= 1.1 在 md 中加粗"""
    text = f"{weight:.1f}"
    if weight >= BOLD_WEIGHT_THRESHOLD:
        return f"**{text}**"
    return text


def _format_display_keywords(route: dict[str, Any]) -> str:
    """取 display_keywords；缺省时回落到 keywords 原样逗号拼接"""
    display = route.get("display_keywords")
    if display:
        return str(display).strip()
    return ", ".join(route.get("keywords", []))


def _render_baseline_section(baseline: list[dict[str, Any]]) -> list[str]:
    """渲染 Tier-0 baseline 表格（无条件必读）"""
    if not baseline:
        return []
    lines: list[str] = [
        "## Tier-0: Baseline (unconditional)",
        "",
        (
            "Every Go service change in `demo-app/` reads these. The router "
            "adds them to the skill list without any matching."
        ),
        "",
        "| Skill | Reason |",
        "|-------|--------|",
    ]
    for item in baseline:
        skill_cell = f"`{item['skill']}`"
        reason_cell = str(item.get("reason", "") or "").strip()
        lines.append(f"| {skill_cell} | {reason_cell} |")
    lines.append("")
    return lines


def _render_conditional_section(conditional: list[dict[str, Any]]) -> list[str]:
    """渲染 Tier-1 conditional 表格（触发器命中即必读，不受 top-K 截断）"""
    if not conditional:
        return []
    lines: list[str] = [
        "## Tier-1: Conditional (trigger fires → mandatory)",
        "",
        (
            "When any of the listed keywords appears in the demand text "
            "(case-insensitive substring), the router marks the skill as "
            "mandatory. These are **not** subject to top-K truncation."
        ),
        "",
        "| Skill | Trigger Keywords | Reason |",
        "|-------|------------------|--------|",
    ]
    for item in conditional:
        skill_cell = f"`{item['skill']}`"
        trigger = item.get("trigger", {}) or {}
        keywords = trigger.get("keywords_any", []) or []
        trigger_cell = ", ".join(str(kw) for kw in keywords)
        reason_cell = str(item.get("reason", "") or "").strip()
        lines.append(f"| {skill_cell} | {trigger_cell} | {reason_cell} |")
    lines.append("")
    return lines


def _render_routes_section(routes: list[dict[str, Any]]) -> list[str]:
    """渲染 Tier-2 weight-based routes 表格"""
    lines: list[str] = [
        "## Tier-2: Routes (weight-based top-K)",
        "",
        (
            "Keyword substring match; multiple matches are sorted by `weight` "
            "DESC and the router keeps the top K (default K = 5). Business "
            "skills (`skills/domain/*`) tie-break by winning generic ones."
        ),
        "",
        "| Keywords / Domain | Ref File | Weight | Description |",
        "|-------------------|----------|--------|-------------|",
    ]
    for route in routes:
        keywords_cell = _format_display_keywords(route)
        skill_cell = f"`{route['skill']}`"
        weight_cell = _format_weight(float(route.get("weight", 1.0)))
        description_cell = str(route.get("description", "") or "").strip()
        lines.append(
            f"| {keywords_cell} | {skill_cell} | {weight_cell} | {description_cell} |"
        )
    lines.append("")
    return lines


def render_skill_routing_markdown(data: dict[str, Any]) -> str:
    """
    将路由数据渲染为 skill-routing.md 文本

    @params:
        data: load_routing() 返回的 dict

    @return:
        完整的 skill-routing.md 文本内容
    """
    baseline: list[dict[str, Any]] = data.get("baseline", []) or []
    conditional: list[dict[str, Any]] = data.get("conditional", []) or []
    routes: list[dict[str, Any]] = data.get("routes", []) or []

    lines: list[str] = [
        AUTO_GENERATED_HEADER,
        "",
        "# Skill Routing Table",
        "",
        "> **⚠️ Source of truth**: `rules/skill-routing.yaml`. This Markdown file",
        "> is a human-readable mirror generated by `scripts/gen_skill_routing_md.py`.",
        "> If the two disagree, the YAML wins. When adding or changing a route,",
        "> edit the YAML and regenerate this file.",
        "",
        (
            "Routing is performed by `pipeline/skills/router.py` (deterministic "
            "code), not by the agent. Agents receive the resolved skill list in "
            "the system prompt and must NOT re-match this table themselves."
        ),
        "",
        "Three tiers:",
        "",
        "1. **Baseline** — unconditional, every Go service change reads these.",
        "2. **Conditional** — mandatory when the trigger keyword fires.",
        "3. **Routes** — weight-based top-K recall for the rest.",
        "",
    ]

    lines.extend(_render_baseline_section(baseline))
    lines.extend(_render_conditional_section(conditional))
    lines.extend(_render_routes_section(routes))

    lines.append(
        f"**Path Prefix**: `{SKILL_PATH_PREFIX}` (relative to the workspace root)"
    )

    return "\n".join(lines) + "\n"


def write_skill_routing(
    yaml_path: Path = ROUTING_YAML_PATH,
    md_path: Path = ROUTING_MD_PATH,
) -> Path:
    """生成并写入 skill-routing.md"""
    content = render_skill_routing_markdown(load_routing(yaml_path))
    md_path.write_text(content, encoding="utf-8")
    return md_path


def check_skill_routing(
    yaml_path: Path = ROUTING_YAML_PATH,
    md_path: Path = ROUTING_MD_PATH,
) -> bool:
    """校验 skill-routing.md 是否与 YAML 一致"""
    expected = render_skill_routing_markdown(load_routing(yaml_path))
    actual = md_path.read_text(encoding="utf-8") if md_path.exists() else ""
    return actual == expected


def main(argv: Optional[list[str]] = None) -> int:
    """运行路由文档生成或一致性校验"""
    parser = argparse.ArgumentParser(
        description=(
            "Generate or check rules/skill-routing.md from rules/skill-routing.yaml"
        ),
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if rules/skill-routing.md is not up to date",
    )
    args = parser.parse_args(argv)

    if args.check:
        if check_skill_routing():
            print(f"Up to date: {ROUTING_MD_PATH}")
            return 0
        print(
            "rules/skill-routing.md is out of date. "
            "Run `python scripts/gen_skill_routing_md.py` to regenerate it.",
            file=sys.stderr,
        )
        return 1

    output_path = write_skill_routing()
    print(f"Generated {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
